sciploreAnalysisBundle:
    resource: "@sciploreAnalysisBundle/Resources/config/routing.yml"
    prefix:   /

#sciploreUIBundle:
#    resource: "@sciploreUIBundle/Controller/"
#    type:     annotation
#    prefix:   /

UserManagementBundle:
    resource: "@sciploreUserManagementBundle/Resources/config/routing.yml"
    prefix:   /
sciploreblogtestBundle:
    resource: "@sciploreUIBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
